### ISSUE TITLE
Pylint throws error on certain files

### ISSUE THREAD

**Issue by jofeinstein** [ucb-rit/coldfront#393]
Running pylint on views, forms, and utils that are in separate files from the main app files throws an error.

```
Traceback (most recent call last):
  File "/vagrant/coldfront_app/venv/lib64/python3.6/site-packages/pylint_django/checkers/foreign_key_strings.py", line 92, in open
    django.setup()
  File "/vagrant/coldfront_app/venv/lib64/python3.6/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/vagrant/coldfront_app/venv/lib64/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/vagrant/coldfront_app/venv/lib64/python3.6/site-packages/django/conf/__init__.py", line 67, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting LOGGING_CONFIG, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vagrant/coldfront_app/venv/lib64/python3.6/site-packages/pylint_django/checkers/foreign_key_strings.py", line 120, in open
    settings.configure(Settings(self.config.django_settings_module))
  File "/vagrant/coldfront_app/venv/lib64/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'coldfront'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vagrant/coldfront_app/venv/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/vagrant/coldfront_app/venv/lib64/python3.6/site-packages/pylint/__init__.py", line 24, in run_pylint
    PylintRun(sys.argv[1:])
  File "/vagrant/coldfront_app/venv/lib64/python3.6/site-packages/pylint/lint/run.py", line 398, in __init__
    linter.check(args)
  File "/vagrant/coldfront_app/venv/lib64/python3.6/site-packages/pylint/lint/pylinter.py", line 997, in check
    self.get_ast, self._iterate_file_descrs(files_or_modules)
  File "/vagrant/coldfront_app/venv/lib64/python3.6/site-packages/pylint/lint/pylinter.py", line 1031, in _check_files
    with self._astroid_module_checker() as check_astroid_module:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/vagrant/coldfront_app/venv/lib64/python3.6/site-packages/pylint/lint/pylinter.py", line 1150, in _astroid_module_checker
    checker.open()
  File "/vagrant/coldfront_app/venv/lib64/python3.6/site-packages/pylint_django/checkers/foreign_key_strings.py", line 127, in open
    args=self.config.django_settings_module,
  File "/vagrant/coldfront_app/venv/lib64/python3.6/site-packages/pylint/checkers/base_checker.py", line 124, in add_message
    msgid, line, node, args, confidence, col_offset, end_lineno, end_col_offset
  File "/vagrant/coldfront_app/venv/lib64/python3.6/site-packages/pylint/lint/pylinter.py", line 1527, in add_message
    end_col_offset,
  File "/vagrant/coldfront_app/venv/lib64/python3.6/site-packages/pylint/lint/pylinter.py", line 1456, in _add_one_message
    self.stats.increase_single_module_message_count(self.current_name, msg_cat, 1)
  File "/vagrant/coldfront_app/venv/lib64/python3.6/site-packages/pylint/utils/linterstats.py", line 296, in increase_single_module_message_count
    self.by_module[modname][type_name] += increase
KeyError: '/vagrant/coldfront_app/coldfront/setup.cfg'

```

**Comment by matthew-li** [comment]
@jofeinstein Thanks for noting this. Can you also include the command you ran that caused this?
