### ISSUE TITLE
New User Registration is not complete

### ISSUE THREAD

**Issue by kmuriki** [ucb-rit/coldfront#47]
Trying to test a new user registration, looks like the user record is created but the user doesn't land on a proper page instead get directed to Django traceback

Request Method: | POST
-- | --
http://127.0.0.1:8000/user/register/?next=
3.1.7
ImproperlyConfigured
Setting CENTER_BASE_URL not found
/root/coldfront_app/coldfront/coldfront/core/utils/common.py, line 24, in import_from_settings
/root/coldfront_app/venv/bin/python
3.6.8
['/root/coldfront_app/coldfront',  '/usr/lib64/python36.zip',  '/usr/lib64/python3.6',  '/usr/lib64/python3.6/lib-dynload',  '/root/coldfront_app/venv/lib64/python3.6/site-packages',  '/root/coldfront_app/venv/lib/python3.6/site-packages']
Fri, 05 Mar 2021 00:49:20 +0000

/tmp/debug.log shows this:

[2021-03-05 00:49:20,593] ERROR log.log_response: Internal Server Error: /user/register/
Traceback (most recent call last):
  File "/root/coldfront_app/coldfront/coldfront/core/utils/common.py", line 22, in import_from_settings
    return getattr(settings, attr)
  File "/root/coldfront_app/venv/lib64/python3.6/site-packages/django/conf/__init__.py", line 83, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'CENTER_BASE_URL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/coldfront_app/venv/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/coldfront_app/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/coldfront_app/venv/lib64/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/coldfront_app/venv/lib64/python3.6/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/root/coldfront_app/venv/lib64/python3.6/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/root/coldfront_app/venv/lib64/python3.6/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/root/coldfront_app/coldfront/coldfront/core/user/views.py", line 327, in form_valid
    send_account_activation_email(self.object)
  File "/root/coldfront_app/coldfront/coldfront/core/user/utils.py", line 147, in send_account_activation_email
    'activation_url': __account_activation_url(user),
  File "/root/coldfront_app/coldfront/coldfront/core/user/utils.py", line 127, in __account_activation_url
    domain = import_from_settings('CENTER_BASE_URL')
  File "/root/coldfront_app/coldfront/coldfront/core/utils/common.py", line 24, in import_from_settings
    raise ImproperlyConfigured('Setting {0} not found'.format(attr))
django.core.exceptions.ImproperlyConfigured: Setting CENTER_BASE_URL not found
[2021-03-05 00:49:20,599] ERROR basehttp.log_message: "POST /user/register/?next= HTTP/1.1" 500 110185
[2021-03-05 00:49:20,635] WARNING log.log_response: Not Found: /favicon.ico
[2021-03-05 00:49:20,636] WARNING basehttp.log_message: "GET /favicon.ico HTTP/1.1" 404 3176

**Comment by matthew-li** [comment]
If `EMAIL_ENABLED` is set to `True`, some additional variables in `local_settings.py` need to be uncommented. In this case, those include `CENTER_NAME`, `CENTER_BASE_URL`, and other `EMAIL_*` settings.

This is less of a bug and more of a configuration issue.

**Comment by kmuriki** [comment]
Yes uncommenting CENTER_BASE_URL resolves this issue. Closing this now.
